config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
  get '/home', to: 'home#index'
  get '/user/:id', to: 'users#show'
  post '/user', to: 'users#follow'
  delete '/user', to: 'users#unfollow'
  get '/followers', to: 'home#followers'
  get '/followings', to: 'home#followings'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follower.rb
class Follower < ApplicationRecord
  belongs_to :user
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :followers
  has_many :followings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
          devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :password])
          devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :password, :current_password])
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = current_user
    @posts = Post.order(created_at: :desc).last(10)
  end
  
  def followers
    @user = current_user
    @follower_records = Follower.where(user_id: @user.id)
    @followers = []
    @follower_records.each do |fr|
      f = User.find_by(id: fr.follower_id)
      @followers.append(f)
    end
  end
  
  def followings
    @user = current_user
    @followings_records = Following.where(user_id: @user.id)
    @followings = []
    @followings_records.each do |fr|
      f = User.find_by(id: fr.following_id)
      @followings.append(f)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @user = current_user
    @posts = Post.where(user_id: @user.id)
  end

  def show
    @user = current_user
    @post = Post.find_by(id: params[:id])
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to @post
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    '/' # Or :prefix_to_your_route
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    unless user_signed_in?
      redirect_to '/users/sign_in'
      return
    end
    id = params[:id]
    @user_view = User.find_by(id: id)
    @user = current_user
    puts "user id: #{@user.id}"
    puts "user_view id: #{@user_view.id}"
    @is_following = true
    relation = Following.where(user_id: @user.id).where(following_id: @user_view.id)
    puts relation
    @is_following = false if relation.blank?
    @posts = Post.where(user_id: id).limit(10)
  end

  def follow
    @user = current_user
    follow_user_id = follow_params.to_i
    @follow_user = User.find_by(id: follow_user_id)
    @following = Following.new(following_id: follow_user_id, user_id: @user.id)
    @follower = Follower.new(follower_id: @user.id, user_id: follow_user_id)
    @following.save
    @follower.save
    redirect_to action: 'show', id: follow_user_id
  end

  def unfollow
    @user = current_user
    follow_user_id = follow_params.to_i
    @follow_user = User.find_by(id: follow_user_id)
    @following = Following.where(following_id: follow_user_id).where(user_id: @user.id).first
    @follower = Follower.where(follower_id: @user.id).where(user_id: follow_user_id).first
    Following.destroy(@following.id)
    Follower.destroy(@follower.id)
    redirect_to action: 'show', id: follow_user_id
  end

  private
    def follow_params
      follow_param = params.require(:follow).permit(:user_id)
      follow_param[:user_id].to_i
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
  <div class="container-fluid">
    <%= link_to 'KNKT+', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
        <%= link_to 'Home', home_path, class: "nav-link" %>
        <% if user_signed_in? then %>
          <%= link_to 'My Posts', '/posts', class: "nav-link" %>
          <%= link_to 'Following', '/followings', class: "nav-link" %>
          <%= link_to 'Followers', '/followers', class: "nav-link" %>
          <%= link_to 'Create Post', new_post_path, class: "nav-link" %>
        <% end %> 
      </div>
      <div class="navbar-nav ms-auto">
        <% if user_signed_in? then %>
          <div class="nav-link">
            <a href="/user/<%= @user.id %>" style="color: inherit; text-decoration: none">
              <%= @user.first_name + ' ' + @user.last_name %>
            </a>
          </div>
          <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
          <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "nav-link" %>
        <% else %> 
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
          <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
        <% end %>  
      </div>
    </div>
  </div>
</nav>

app/views/home/followers.html.erb
<h2>Followers List</h2>
<ul class="list-group col-6">
  <% @followers.each do |fr| %>
    <li class="list-group-item"><a href="/user/<%= fr.id %>"><h3><%= fr.first_name + ' ' + fr.last_name %></h3></a></li>
  <% end %>   
</ul>

app/views/home/followings.html.erb
<h2>Followings List</h2>
<ul class="list-group col-6">
  <% @followings.each do |fr| %>
  <li class="list-group-item"><a href="/user/<%= fr.id %>"><h3><%= fr.first_name + ' ' + fr.last_name %></h3></a></li>
  <% end %>   
</ul>

app/views/home/index.html.erb
<h2>WELCOME TO KNKT+</h2>
<h2>Recent Posts</h2>

<ul>
  <% @posts.each do |post| %>
  <div class="card w-50">
    <div class="card-body">
      <h3 class="card-title"><%= post.title %></h3>
      <h5 class="card-text">- by <a href="/user/<%= post.user_id %>"><%= post.user.first_name %> <%= post.user.last_name %></a></h5>
      <a href="/posts/<%= post.id%>" class="btn btn-primary">View Post</a>
    </div>
  </div>
  <% end %> 
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "styles.css" %>
    <title>KNKT+</title>
  </head>
  <body>
    <%= render'home/navbar' %> 
    <div class="container mt-3">
      <%= yield %>
    </div>

    <div class="footer">
      <span class="footer-text">© Made By Hardik Sharma</span>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<h2>My Posts</h2>
<div class="card col-6">
  <ul class="list-group list-group-flush">
    <% @posts.each do |post| %>
     <li class="list-group-item"><a href="/posts/<%= post.id %>"><h3><%= post.title %> </h3></a></li>
    <% end %> 
  </ul>
</div>
<ul>
   
</ul>

app/views/posts/new.html.erb
<h2>Create a new Post!</h2>
<div class="col-8">
<form action="/posts" method="post">
  <input type="hidden" name="post[user]" value="<%= @user.id %>">
  <div>
    <label for="post_title" class="form-label">Title</label><br>
    <input type="text" name="post[title]" id="post_title" class="form-control">
  </div>
  <div>
    <label for="post_body" class="form-label">Body</label><br>
    <textarea name="post[body]" id="post_body" class="form-control" rows=15></textarea>
  </div>
  <br>
  <input type="submit" value="Create" class="btn btn-primary">
</form>
</div>

app/views/posts/show.html.erb
<h2><%= @post.title %> </h2>
<h3>Author: <a href="/user/<%= @post.user.id %>"><%= @post.user.first_name + ' ' + @post.user.last_name %></a> </h3>
<hr>
<h3><%= @post.body %> </h3>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<h2><%= @user_view.first_name + ' ' + @user_view.last_name %> </h2>
<h3>Email: <%= @user_view.email %> </h3>
<% if @is_following %>
  <h4>Following</h4>
  <form action="/user" method="post">
    <input type="hidden" name="follow[user_id]" value="<%= @user_view.id %>">
    <input type="hidden" name="_method" value="delete">
    <button type="submit" class="btn btn-danger">x Unfollow</button>
  </form>
<% elsif @user.id == @user_view.id %>
  <h2> </h2>
<% else %>
  <form action="/user" method="post">
    <input type="hidden" name="follow[user_id]" value="<%= @user_view.id %>">
    <button type="submit" class="btn btn-primary">Follow+</button>
  </form>
<% end %>
<hr>
<h3>User Posts</h3>
<ul>
  <% @posts.each do |post| %>
  <div class="card w-50">
    <div class="card-body">
      <h3 class="card-title"><%= post.title %></h3>
      <h5 class="card-text">- by <a href="/user/<%= post.user_id %>"><%= post.user.first_name %> <%= post.user.last_name %></a></h5>
      <a href="/posts/<%= post.id%>" class="btn btn-primary">View Post</a>
    </div>
  </div>
  <% end %> 
</ul>